### ISSUE TITLE
Voronoi throws error

### ISSUE THREAD

**Issue by schoeller** [aerispaha/trace#16]
Dear all,

I am not sure whether this is an issues or misjudgement. I am trying to create a sewergraph mockup from an OSM road network. I have done the following:

```
#1 fetch data through osmnx
G = ox.graph_from_address('Bandung, Jawa, Indonesia', distance=1000, network_type='drive', infrastructure='way["highway"~"motorway|trunk|primary|secondary|tertiary|unclassified|residential"]')

#2 add elevation to nodes and edges from Google Maps
G = ox.add_node_elevations(G, YOUR_MAPS_KEY, max_locations_per_batch=350, pause_duration=0.02)

#3 adding grades to edges
G = ox.add_edge_grades(G)

#4 converting graph to geodataframes through sewergraph. This could also be done through gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)
gdf_nodes = sg.gdf_from_graph(G, 'nodes')
gdf_edges = sg.gdf_from_graph(G, 'edges')

#5 generating Voronoi surfaces from edges 
sg.drainage_areas_from_sewers(gdf_edges,'osmid')
```

The last command is throwing errors as follows. Any hints on how to resolve this are highly welcome.

Best 

Sebastian

```
sewersdf1.crs: {'init': 'epsg:2272'}, sheds.crs: {'init': 'epsg:2272'}
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 114, in _cython_agg_blocks
    block.values, how, axis=agg_axis, min_count=min_count)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 548, in aggregate
    min_count=min_count)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 453, in _cython_operation
    out_shape = (self.ngroups,) + values.shape[1:]
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 279, in ngroups
    return len(self.result_index)
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 291, in result_index
    return self.groupings[0].result_index.rename(self.names[0])
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 376, in result_index
    return self.group_index
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 381, in group_index
    self._make_labels()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 392, in _make_labels
    self.grouper, sort=self.sort)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\util\_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 613, in factorize
    na_value=na_value)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 460, in _factorize_array
    na_value=na_value)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1792, in pandas._libs.hashtable.PyObjectHashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1712, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 1257, in f
    alias, alt=npfunc, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 70, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only, min_count=min_count)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 136, in _cython_agg_blocks
    result = block._try_coerce_and_cast_result(result)
UnboundLocalError: local variable 'result' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 201, in aggregate
    [arg], _level=_level, _axis=self.axis)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\base.py", line 617, in _aggregate_multiple_funcs
    raise ValueError("no results")
ValueError: no results

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 226, in _aggregate_generic
    for name, data in self:
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 143, in get_iterator
    splitter = self._get_splitter(data, axis=axis)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 149, in _get_splitter
    comp_ids, _, ngroups = self.group_info
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 252, in group_info
    comp_ids, obs_group_ids = self._get_compressed_labels()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 268, in _get_compressed_labels
    all_labels = [ping.labels for ping in self.groupings]
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 268, in <listcomp>
    all_labels = [ping.labels for ping in self.groupings]
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 367, in labels
    self._make_labels()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 392, in _make_labels
    self.grouper, sort=self.sort)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\util\_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 613, in factorize
    na_value=na_value)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 460, in _factorize_array
    na_value=na_value)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1792, in pandas._libs.hashtable.PyObjectHashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1712, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\sewergraph\area_calcs.py", line 94, in drainage_areas_from_sewers
    sewer_sheds = sewer_sheds.dissolve(by=SEWER_ID_COL, aggfunc='sum', as_index=False)
  File "C:\ProgramData\Miniconda3\lib\site-packages\geopandas\geodataframe.py", line 565, in dissolve
    aggregated_data = data.groupby(by=by).agg(aggfunc)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 1315, in aggregate
    return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 186, in aggregate
    result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\base.py", line 356, in _aggregate
    **kwargs), None
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\base.py", line 312, in _try_aggregate_string_function
    return f(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 1262, in f
    lambda x: npfunc(x, axis=self.axis))
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 1315, in aggregate
    return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 206, in aggregate
    result = self._aggregate_generic(arg, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 230, in _aggregate_generic
    return self._aggregate_item_by_item(func, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 274, in _aggregate_item_by_item
    raise errors
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 259, in _aggregate_item_by_item
    colg.aggregate(func, *args, **kwargs), data)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 778, in aggregate
    result = self._aggregate_named(func_or_funcs, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\generic.py", line 905, in _aggregate_named
    for name, group in self:
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 143, in get_iterator
    splitter = self._get_splitter(data, axis=axis)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 149, in _get_splitter
    comp_ids, _, ngroups = self.group_info
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 252, in group_info
    comp_ids, obs_group_ids = self._get_compressed_labels()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 268, in _get_compressed_labels
    all_labels = [ping.labels for ping in self.groupings]
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\ops.py", line 268, in <listcomp>
    all_labels = [ping.labels for ping in self.groupings]
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 367, in labels
    self._make_labels()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 392, in _make_labels
    self.grouper, sort=self.sort)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\util\_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 613, in factorize
    na_value=na_value)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 460, in _factorize_array
    na_value=na_value)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1792, in pandas._libs.hashtable.PyObjectHashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1712, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'list'
```

**Comment by schoeller** [comment]
I have managed to work my way around it customizing code. OSM road network is read, Voronoi is generated and player back ontop of the MultiDiGraph. Since this graph type seems unusable for sewergraph, so I am missing something basic. I will have to dig further I guess.

**Comment by aerispaha** [comment]
Hi @schoeller, thanks for raising this issue! `sewergraph` certainly needs to be updated to support MultiDiGraph networks as it is very common in water/sewer networks to have multiple edges between the same two nodes. I've raised an issue to address this: #17. 

Regardless, it looks like the fundamental issue causing this error is due to the fact that some of the `osmid` values are list types. Here's an example: 
![image](https://user-images.githubusercontent.com/6521360/54079112-e9230680-42a3-11e9-8095-e0770722156c.png)


I was able to get the `sg.drainage_area_from_sewers` function to work by creating a new column in the edge GeoDataFrame that I know has unique values, without any lists:

```python 
# fetch data through osmnx
G = ox.graph_from_address('Bandung, Jawa, Indonesia', distance=1000, network_type='drive', infrastructure='way["highway"~"motorway|trunk|primary|secondary|tertiary|unclassified|residential"]')

# create GeoDataFrames of nodes and edges 
gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)

# force a unique ID for each edge 
gdf_edges['facilityid'] = gdf_edges.apply(lambda row: sg.generate_facility_id(), axis=1)

#5 generating Voronoi surfaces from edges, using unique ID to dictate bounds of each polygon 
sheds = sg.drainage_areas_from_sewers(gdf_edges,'facilityid')
```

Here's what the resulting `sheds` polygon data looks like with the roads superimposed in red:
![image](https://user-images.githubusercontent.com/6521360/54079209-d5c56a80-42a6-11e9-8c92-6cec8da83b47.png)

There still are some limitations and unexpected behavior from the sparsely tested area_calcs module (for example, there are small regions without any polygon coverage for some reason). But for now, hopefully this work around will help you.
